rtl/common/primitives/gates.sv
rtl/common/primitives/adder.sv
rtl/common/primitives/register.sv
rtl/common/primitives/vector_register.sv
rtl/common/scalar/alu.sv
rtl/common/scalar/register_file.sv
rtl/common/control/control_fsm.sv
rtl/cpu/control/decoder.sv
rtl/cpu/control/program_counter.sv
rtl/cpu/control/control_unit.sv
rtl/cpu/datapath/vector_register_file.sv
rtl/cpu/datapath/vector_alu.sv
rtl/cpu/datapath/datapath.sv
rtl/cpu/cpu.sv
rtl/gpu/warp/warp_decoder.sv
rtl/gpu/warp/warp_lane.sv
rtl/gpu/warp/warp_datapath.sv
rtl/gpu/warp/warp_control_unit.sv
rtl/gpu/warp/warp.sv
rtl/gpu/gpu.sv
rtl/memory/memory.sv
rtl/top/chip.sv
rtl/top/fpga_gemm_top.sv
